# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-11 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='status',
            field=models.IntegerField(choices=[(1, 'daily'), (2, 'weekly'), (3, 'monthly')], default=1),
        ),
    ]
