# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-11 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0004_auto_20170911_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='payout_frequency',
            field=models.IntegerField(choices=[(1, 'daily'), (2, 'weekly'), (3, 'monthly')], default=2),
        ),
    ]
