# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 13:33
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0005_auto_20170911_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='wallet',
            field=models.CharField(blank=True, default='', max_length=34, unique=True, validators=[django.core.validators.RegexValidator('A[0-9a-zA-Z]{33}$', 'Only valid address formats are allowed.')]),
        ),
    ]
