# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-06 11:43
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0007_auto_20171023_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='main_ark_tag',
            field=models.CharField(blank=True, default=None, max_length=34),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='receiving_ark_address',
            field=models.CharField(blank=True, default='', max_length=34, validators=[django.core.validators.RegexValidator('A[0-9a-zA-Z]{33}$', 'Only valid address formats are allowed.')]),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='receiving_ark_address_tag',
            field=models.CharField(blank=True, default=None, max_length=34),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='receiving_ark_address_verified',
            field=models.BooleanField(default=False),
        ),
    ]
