# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-14 11:25
from __future__ import unicode_literals

import annoying.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0007_auto_20171023_2001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='id',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ark_send_to_second_address',
            field=models.IntegerField(choices=[(1, 'Send payout second address'), (2, 'Send payout to voting address')], default=2),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='main_ark_tag',
            field=models.CharField(blank=True, max_length=34, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='receiving_ark_address',
            field=models.CharField(blank=True, max_length=34, null=True, validators=[django.core.validators.RegexValidator('A[0-9a-zA-Z]{33}$', 'Only valid address formats are allowed.')]),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='receiving_ark_address_tag',
            field=models.CharField(blank=True, max_length=34, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='receiving_ark_address_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
