# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-14 23:17
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0008_auto_20171114_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='main_ark_wallet',
            field=models.CharField(blank=True, max_length=34, unique=True, validators=[django.core.validators.RegexValidator('A[0-9a-zA-Z]{33}$', 'Only valid address formats are allowed.')]),
        ),
    ]
