# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-06 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0009_auto_20171106_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='receiving_ark_address_tag',
            field=models.CharField(blank=True, max_length=34, null=True),
        ),
    ]
