# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-06 16:59
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0010_auto_20171106_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='receiving_ark_address',
            field=models.CharField(blank=True, max_length=34, null=True, validators=[django.core.validators.RegexValidator('A[0-9a-zA-Z]{33}$', 'Only valid address formats are allowed.')]),
        ),
    ]
