# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-03 20:52
from __future__ import unicode_literals

import console.custom_model_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0010_auto_20171115_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='preferred_day',
            field=console.custom_model_fields.DayOfTheWeekField(choices=[('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday'), ('6', 'Saturday'), ('7', 'Sunday'), ('8', 'No preferred day')], default='8', max_length=1),
        ),
    ]
