# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-03 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0011_userprofile_preferred_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='inform_by_email',
            field=models.IntegerField(default=1),
        ),
    ]
