# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-06 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0011_auto_20171106_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ark_send_to_second_address',
            field=models.BooleanField(default=False),
        ),
    ]
