# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-06 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0012_userprofile_ark_send_to_second_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='ark_send_to_second_address',
            field=models.IntegerField(choices=[(1, 'Send payout second address'), (2, 'Send payout to voting address')], max_length=1),
        ),
    ]
