# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-03 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0012_userprofile_inform_by_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='payout_frequency',
            field=models.IntegerField(choices=[(1, 'daily'), (2, 'weekly'), (3, 'monthly')], default=2, help_text='Monthly payouts are awarded a bonus due to decreased transaction fees.'),
        ),
    ]
