# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-05 05:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0014_auto_20171204_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='send_email_about_payout',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ark_send_to_second_address',
            field=models.IntegerField(choices=[(1, 'Send payout second address.'), (2, 'Send payout to voting address.')], default=2),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='inform_by_email',
            field=models.IntegerField(choices=[(1, "Don't inform me by email about payouts and current news."), (2, 'Feel free to send me emails.')], default=1),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='payout_frequency',
            field=models.IntegerField(choices=[(1, 'daily'), (2, 'weekly'), (3, 'monthly')], default=2),
        ),
    ]
