# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-11 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0015_auto_20171205_0634'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='tx_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
