# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-14 11:25
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArkDelegates',
            fields=[
                ('pubkey', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, default='', max_length=34, unique=True, validators=[django.core.validators.RegexValidator('A[0-9a-zA-Z]{33}$', 'Only valid address formats are allowed.')])),
                ('voters', models.IntegerField(default=1)),
                ('productivity', models.FloatField(default=100)),
                ('ark_votes', models.FloatField(default=0)),
                ('producedblocks', models.IntegerField(default=0)),
                ('missedblocks', models.IntegerField(default=0)),
                ('rank', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CronTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_result', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DutchDelegateStatus',
            fields=[
                ('id', models.CharField(default='main', max_length=10, primary_key=True, serialize=False)),
                ('rank', models.IntegerField(default=1)),
                ('ark_votes', models.FloatField(default=0)),
                ('voters', models.IntegerField(default=0)),
                ('productivity', models.FloatField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.CharField(default='main', max_length=10, primary_key=True, serialize=False)),
                ('blockchain_height', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='VotePool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ark_address', models.CharField(blank=True, default='', max_length=34, unique=True, validators=[django.core.validators.RegexValidator('A[0-9a-zA-Z]{33}$', 'Only valid address formats are allowed.')])),
                ('payout_amount', models.FloatField(default=0)),
            ],
        ),
    ]
