# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-14 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ark_delegate_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dutchdelegatestatus',
            name='reward',
            field=models.IntegerField(default=0),
        ),
    ]
