# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-06 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ark_delegate_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DutchDelegateStatus',
            fields=[
                ('id', models.CharField(default='main', max_length=10, primary_key=True, serialize=False)),
                ('rank', models.IntegerField(default=1)),
                ('ark_votes', models.FloatField(default=0)),
                ('voters', models.IntegerField(default=0)),
                ('productivity', models.FloatField(default=100)),
            ],
        ),
    ]
