# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-12 18:05
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ark_delegate_manager', '0002_dutchdelegatestatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArkDelegates',
            fields=[
                ('username', models.CharField(max_length=100)),
                ('pubkey', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('address', models.CharField(blank=True, default='', max_length=34, unique=True, validators=[django.core.validators.RegexValidator('A[0-9a-zA-Z]{33}$', 'Only valid address formats are allowed.')])),
                ('voters', models.IntegerField(default=1)),
                ('productivity', models.FloatField(default=100)),
                ('ark_votes', models.FloatField(default=0)),
                ('producedblocks', models.IntegerField(default=0)),
                ('missedblocks', models.IntegerField(default=0)),
                ('rank', models.IntegerField(default=0)),
            ],
        ),
    ]
