# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-25 00:06
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ark_delegate_manager', '0002_dutchdelegatestatus_reward'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistedAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ark_address', models.CharField(blank=True, default='', max_length=34, unique=True, validators=[django.core.validators.RegexValidator('A[0-9a-zA-Z]{33}$', 'Only valid address formats are allowed.')])),
                ('info', models.CharField(blank=True, default='', max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='EarlyAdopterAddressException',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_ark_address', models.CharField(blank=True, default='', max_length=34, validators=[django.core.validators.RegexValidator('A[0-9a-zA-Z]{33}$', 'Only valid address formats are allowed.')])),
                ('new_ark_address', models.CharField(blank=True, default='', max_length=34, unique=True, validators=[django.core.validators.RegexValidator('A[0-9a-zA-Z]{33}$', 'Only valid address formats are allowed.')])),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('info', models.CharField(blank=True, default='', max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.CharField(default='main', max_length=10, primary_key=True, serialize=False)),
                ('vendorfield', models.CharField(default='Thank you for voting.', max_length=64)),
            ],
        ),
        migrations.DeleteModel(
            name='CronTest',
        ),
        migrations.AlterField(
            model_name='arkdelegates',
            name='productivity',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='arkdelegates',
            name='voters',
            field=models.IntegerField(default=0),
        ),
    ]
