# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-25 23:18
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ark_delegate_manager', '0003_auto_20171125_0106'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentLock',
            fields=[
                ('id', models.CharField(default='main', max_length=10, primary_key=True, serialize=False)),
                ('lock', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PayoutTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=34, unique=True, validators=[django.core.validators.RegexValidator('A[0-9a-zA-Z]{33}$', 'Only valid address formats are allowed.')])),
                ('amount', models.IntegerField(default=0)),
                ('last_payout_blockchain_side', models.IntegerField(default=0)),
                ('vote_timestamp', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=False)),
                ('last_payout_server_side', models.IntegerField(default=0)),
            ],
        ),
    ]
