# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-26 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ark_delegate_manager', '0004_paymentlock_payouttable'),
    ]

    operations = [
        migrations.CreateModel(
            name='CronLock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(blank=True, max_length=10, unique=True)),
                ('lock', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='PaymentLock',
        ),
    ]
