# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-26 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ark_delegate_manager', '0005_auto_20171126_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cronlock',
            name='job_name',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
