# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-05 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ark_delegate_manager', '0008_auto_20171126_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='news_link',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
