# Generated by Django 2.0 on 2018-01-07 12:35

import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ark_delegate_manager', '0009_setting_news_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomAddressExceptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_ark_address', models.CharField(blank=True, default='', max_length=34, validators=[django.core.validators.RegexValidator('A[0-9a-zA-Z]{33}$', 'Only valid address formats are allowed.')])),
                ('new_ark_address', models.CharField(blank=True, default='', max_length=34, unique=True, validators=[django.core.validators.RegexValidator('A[0-9a-zA-Z]{33}$', 'Only valid address formats are allowed.')])),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('info', models.CharField(blank=True, default='', max_length=10000)),
                ('share_RANGE_IS_0_TO_1', models.IntegerField(default=0.95)),
            ],
        ),
        migrations.DeleteModel(
            name='EarlyAdopterAddressException',
        ),
        migrations.AddField(
            model_name='arkdelegates',
            name='share_percentages',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={999999999999999999: 'N.A.'}),
        ),
    ]
