# Generated by Django 2.0 on 2018-01-07 19:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ark_delegate_manager', '0010_auto_20180107_1335'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlacklistedAddress',
        ),
        migrations.AddField(
            model_name='customaddressexceptions',
            name='status_name',
            field=models.CharField(default='Early Adopter', max_length=100),
        ),
        migrations.AddField(
            model_name='votepool',
            name='blacklisted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='votepool',
            name='share',
            field=models.IntegerField(default=0.95),
        ),
        migrations.AddField(
            model_name='votepool',
            name='status',
            field=models.CharField(default='Non-Dutchdelegate Voter', max_length=200),
        ),
        migrations.AlterField(
            model_name='customaddressexceptions',
            name='new_ark_address',
            field=models.OneToOneField(blank=True, default='', max_length=34, on_delete=django.db.models.deletion.CASCADE, to='ark_delegate_manager.VotePool', validators=[django.core.validators.RegexValidator('A[0-9a-zA-Z]{33}$', 'Only valid address formats are allowed.')]),
        ),
        migrations.AlterField(
            model_name='customaddressexceptions',
            name='share_RANGE_IS_0_TO_1',
            field=models.IntegerField(default=0.96),
        ),
    ]
