# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-16 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ark_delegate_manager', '0012_auto_20180116_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='payouttable',
            name='frequency',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='payouttable',
            name='preferred_day',
            field=models.IntegerField(default=8),
        ),
        migrations.AddField(
            model_name='payouttable',
            name='share',
            field=models.FloatField(default=0.95),
        ),
    ]
